; generated by Slic3r 1.3.1-dev on 2019-10-25 at 17:35:32

; external perimeters extrusion width = 0.33mm (0.48mm^3/s)
; perimeters extrusion width = 0.34mm (0.49mm^3/s)
; infill extrusion width = 0.34mm (0.49mm^3/s)
; solid infill extrusion width = 0.34mm (0.07mm^3/s)
; top infill extrusion width = 0.34mm (0.07mm^3/s)

G28 ; Home all axes 
M109 S200 ; wait for temperature to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G1 Z10 F500; move plate down
G1 Z1.0 F500;
G92 E0
; Filament gcode

; Filament gcode

G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
G92 E0
T1
G1 Z0.250 F480.000
G1 X-3.403 Y1.701 F480.000
G1 F420
G1 X-3.560 Y1.358 E0.04722
G1 X-3.486 Y1.305 E0.05858
G1 X-0.649 Y3.666 E0.51996
G1 X-0.688 Y3.748 E0.53131
G1 X-1.232 Y3.606 E0.60163
G1 X-1.445 Y3.525 E0.63016
G1 X-1.866 Y3.321 E0.68859
G1 X-2.061 Y3.203 E0.71709
G1 X-2.436 Y2.928 E0.77517
G1 X-2.811 Y2.568 E0.84025
G1 X-3.072 Y2.253 E0.89127
G1 X-3.202 Y2.064 E0.92000
G1 X-3.384 Y1.742 E0.96627
G92 E0
G1 X-2.849 Y2.147 F480.000
G1 F420
G1 X-2.600 Y2.354 E0.04040
G1 X-2.643 Y2.396 E0.04790
G1 X-2.411 Y2.620 E0.08814
G1 X-2.352 Y2.561 E0.09863
G1 X-2.103 Y2.767 E0.13903
G1 X-2.166 Y2.829 E0.15003
G1 X-1.901 Y3.020 E0.19078
G1 X-1.855 Y2.974 E0.19895
G1 X-1.607 Y3.181 E0.23934
G1 Z0.500 F480.000
G92 E0
G1 X-3.718 Y0.754 F480.000
G1 F420
G1 X-3.718 Y0.754 E0.00000

G1 F420
G1 X-3.773 Y0.479 E0.05053
G1 X-3.805 Y-0.115 E0.15757
G1 X-3.765 Y-0.573 E0.24023
G1 X-3.688 Y-0.910 E0.30250
G1 X1.565 Y3.461 E1.53256
G1 X1.248 Y3.599 E1.59483
G1 X0.803 Y3.721 E1.67778
G1 X0.344 Y3.790 E1.76136
G1 X-0.060 Y3.798 E1.83407

G1 F420
G1 X-0.344 Y3.790 E1.88416
G1 X-0.799 Y3.721 E1.96518
G1 X-1.170 Y3.620 E2.03279
G1 X-1.455 Y3.518 E2.08610
G1 X-1.872 Y3.316 E2.16747
G1 X-2.064 Y3.200 E2.20695
G1 X-2.435 Y2.927 E2.28805
G1 X-2.769 Y2.613 E2.36870
G1 X-3.065 Y2.259 E2.44983
G1 X-3.191 Y2.076 E2.48902
G1 X-3.479 Y1.539 E2.59614
G1 X-3.664 Y1.028 E2.69178
G1 X-3.710 Y0.798 E2.73294
G92 E0
G1 X-3.348 Y1.073 F480.000
G1 F420
G1 X-0.885 Y3.123 E0.57678
G1 X-3.476 Y0.532 E1.23626
G1 X-3.513 Y0.082 E1.31758
G1 X-0.078 Y3.517 E2.19201
G1 X0.328 Y3.509 E2.26499
G1 X-3.505 Y-0.324 E3.24051
G1 X-3.499 Y-0.387 E3.25194
G1 X-1.446 Y1.321 E3.73266
G1 X0.687 Y3.454 E4.27565
G92 E0
G1 X1.017 Y3.371 F480.000
G1 F420
G1 X1.017 Y3.371 E0.00001
G92 E0
G1 X-1.132 Y3.335 F480.000
G1 F420
G1 X-3.054 Y1.736 E0.45021
G1 X-2.951 Y1.929 E0.48964
G1 X-2.750 Y2.198 E0.55009
G1 X-2.186 Y2.761 E0.69355
G1 X-2.564 Y2.420 E0.78527
G1 X-2.750 Y2.198 E0.83735
G1 Z0.750 F480.000
G92 E0
G1 X-2.798 Y1.551 F480.000
G1 F420
G1 X-3.758 Y0.752 E0.21965
G1 X-3.814 Y0.378 E0.28620
G1 X-3.830 Y-0.084 E0.36756
G1 X-3.798 Y-0.476 E0.43666
G1 X-3.750 Y-0.771 E0.48937
G1 X-3.614 Y-1.258 E0.57830

G1 F420
G1 X-3.456 Y-1.648 E0.65405
G1 X-3.232 Y-2.056 E0.73778
G1 X-2.968 Y-2.410 E0.81725
G1 X2.914 Y2.484 E2.19461
G1 X2.778 Y2.641 E2.23197
G1 X2.435 Y2.956 E2.31569
G1 X2.059 Y3.227 E2.39925
G1 X1.890 Y3.321 E2.43408

G1 F420
G1 X1.653 Y3.453 E2.48163
G1 X1.225 Y3.628 E2.56313
G1 X0.779 Y3.751 E2.64451
G1 X0.322 Y3.820 E2.72579
G1 X-0.056 Y3.832 E2.79233
G1 X-2.763 Y1.579 E3.41187
G92 E0
G1 X-3.474 Y-0.713 F480.000
G1 F420
G1 X-3.246 Y-0.522 E0.05354
G1 X-3.536 Y-0.232 E0.12736
G1 X-3.539 Y0.190 E0.20342
G1 X-3.017 Y-0.332 E0.33639
G1 X-2.788 Y-0.142 E0.38992
G1 X-3.501 Y0.570 E0.57127
G1 X-3.496 Y0.604 E0.57743
G1 X-3.288 Y0.777 E0.62599
G1 X-2.560 Y0.048 E0.81144
G1 X-2.331 Y0.239 E0.86498
G1 X-3.060 Y0.967 E1.05044
G1 X-2.831 Y1.157 E1.10397
G1 X-2.102 Y0.429 E1.28943
G1 X-1.874 Y0.619 E1.34296
G1 X-2.602 Y1.348 E1.52842
G1 X-2.374 Y1.538 E1.58196
G1 X-1.645 Y0.809 E1.76741
G1 X-1.417 Y0.999 E1.82095
G1 X-2.145 Y1.728 E2.00641
G1 X-1.917 Y1.918 E2.05994
G1 X-1.188 Y1.190 E2.24540
G1 X-0.959 Y1.380 E2.29893
G1 X-1.688 Y2.108 E2.48439
G1 X-1.459 Y2.299 E2.53793
G1 X-0.731 Y1.570 E2.72338
G1 X-0.502 Y1.760 E2.77692
G1 X-1.231 Y2.489 E2.96238
G1 X-1.002 Y2.679 E3.01591
G1 X-0.273 Y1.951 E3.20137
G1 X-0.045 Y2.141 E3.25490
G1 X-0.773 Y2.869 E3.44036
G1 X-0.545 Y3.060 E3.49390
G1 X0.184 Y2.331 E3.67935
G1 X0.412 Y2.521 E3.73289
G1 X-0.316 Y3.250 E3.91835
G1 X-0.087 Y3.440 E3.97188
G1 X0.641 Y2.712 E4.15734
G1 X0.870 Y2.902 E4.21087
G1 X0.230 Y3.541 E4.37370
G1 X0.714 Y3.476 E4.46160
G1 X1.098 Y3.092 E4.55942
G1 X1.327 Y3.282 E4.61295
G92 E0
G1 X2.503 Y2.511 F480.000
G1 F420
G1 X2.279 Y2.322 E0.05289
G1 X1.550 Y3.050 E0.23835
G1 X1.324 Y2.862 E0.29127
G1 X2.053 Y2.133 E0.47673
G1 X1.827 Y1.945 E0.52966
G1 X1.098 Y2.674 E0.71512
G1 X0.872 Y2.486 E0.76804
G1 X1.601 Y1.757 E0.95350
G1 X1.375 Y1.569 E1.00643
G1 X0.646 Y2.298 E1.19189
G1 X0.420 Y2.110 E1.24481
G1 X1.149 Y1.381 E1.43027
G1 X0.923 Y1.193 E1.48320
G1 X0.194 Y1.922 E1.66866
G1 X-0.032 Y1.734 E1.72158
G1 X0.696 Y1.005 E1.90704
G1 X0.470 Y0.817 E1.95997
G1 X-0.258 Y1.546 E2.14542
G1 X-0.484 Y1.357 E2.19835
G1 X0.244 Y0.629 E2.38381
G1 X0.018 Y0.441 E2.43674
G1 X-0.710 Y1.169 E2.62219
G1 X-0.936 Y0.981 E2.67512
G1 X-0.208 Y0.253 E2.86058
G1 X-0.434 Y0.065 E2.91351
G1 X-1.162 Y0.793 E3.09896
G1 X-1.388 Y0.605 E3.15189
G1 X-0.660 Y-0.123 E3.33735
G1 X-0.886 Y-0.311 E3.39028
G1 X-1.614 Y0.417 E3.57573
G1 X-1.840 Y0.229 E3.62866
G1 X-1.112 Y-0.500 E3.81412
G1 X-1.338 Y-0.688 E3.86705
G1 X-2.066 Y0.041 E4.05250
G1 X-2.292 Y-0.147 E4.10543
G1 X-1.564 Y-0.876 E4.29089
G1 X-1.790 Y-1.064 E4.34382
G1 X-2.518 Y-0.335 E4.52927
G1 X-2.744 Y-0.523 E4.58220
G1 X-2.016 Y-1.252 E4.76766
G1 X-2.242 Y-1.440 E4.82058
G1 X-2.970 Y-0.711 E5.00604
G1 X-3.197 Y-0.899 E5.05897
G1 X-2.468 Y-1.628 E5.24443
G1 X-2.694 Y-1.816 E5.29735
G1 X-3.349 Y-1.161 E5.46415
G1 X-3.201 Y-1.528 E5.53532
G1 X-2.995 Y-1.904 E5.61253
G1 X-2.920 Y-2.004 E5.63510
G1 Z1.000 F480.000
G92 E0
G1 X1.700 Y3.194 F480.000
G1 F420
G1 X-3.632 Y-1.242 E1.22036
G1 X-3.573 Y-1.406 E1.25103
G1 X-3.374 Y-1.827 E1.33297
G1 X-3.127 Y-2.221 E1.41469
G1 X-2.766 Y-2.651 E1.51353

G1 F420
G1 X-2.323 Y-3.053 E1.62119
G1 X-1.938 Y-3.314 E1.70492
G1 X-1.689 Y-3.445 E1.75546
G1 X3.695 Y1.035 E3.01616
G1 X3.612 Y1.303 E3.06670
G1 X3.424 Y1.731 E3.15078
G1 X3.109 Y2.237 E3.25806

G1 F420
G1 X2.752 Y2.671 E3.35691
G1 X2.410 Y2.985 E3.43863
G1 X2.033 Y3.258 E3.52056
G1 X1.882 Y3.346 E3.55123
G1 X1.735 Y3.223 E3.58488
G92 E0
G1 X2.461 Y2.557 F480.000
G1 F420
G1 X-0.100 Y-0.004 E0.65190
G1 X-2.765 Y-2.221 E1.27593
G1 X-2.774 Y-2.210 E1.27854
G1 X2.216 Y2.779 E2.54867
G1 X1.944 Y2.976 E2.60900
G1 X-2.971 Y-1.940 E3.86020
G1 X-3.148 Y-1.648 E3.92154
G1 X-0.511 Y0.989 E4.59270
G1 X-3.298 Y-1.331 E5.24532
G92 E0
G1 X2.687 Y2.315 F480.000
G1 F420
G1 X2.687 Y2.315 E0.00001
G92 E0
G1 X3.235 Y1.462 F480.000
G1 F420
G1 X0.595 Y-1.178 E0.67196
G1 X-1.725 Y-3.109 E1.21528
G1 X-1.775 Y-3.082 E1.22544
G1 X3.080 Y1.773 E2.46139
G1 X2.894 Y2.053 E2.52188
G1 X-2.054 Y-2.896 E3.78156
G1 X-2.315 Y-2.690 E3.84128
G1 X0.220 Y-0.156 E4.48651
G1 X-2.555 Y-2.465 E5.13633
G92 E0
G1 X3.370 Y1.131 F480.000
G1 F420
G1 X3.371 Y1.131 E0.00001
G1 Z1.250 F480.000
G92 E0
G1 X3.764 Y0.683 F480.000
G1 F420
G1 X3.660 Y1.114 E0.07796
G1 X3.500 Y1.549 E0.15957
G1 X3.289 Y1.961 E0.24111
G1 X3.090 Y2.252 E0.30302
G1 X-2.780 Y-2.633 E1.64657
G1 X-2.347 Y-3.024 E1.74921
G1 X-1.963 Y-3.284 E1.83087
G1 X-1.551 Y-3.497 E1.91244
G1 X-1.350 Y-3.572 E1.95020

G1 F420
G1 X-1.118 Y-3.660 E1.99492
G1 X-0.668 Y-3.769 E2.07815
G1 X-0.208 Y-3.825 E2.16163
G1 X0.395 Y-3.810 E2.27009
G1 X3.675 Y-1.081 E3.03819
G1 X3.764 Y-0.717 E3.10558
G1 X3.820 Y-0.259 E3.18866
G1 X3.822 Y0.203 E3.27183
G1 X3.771 Y0.638 E3.35066

G92 E0
G1 X3.506 Y0.480 F480.000
G1 F420
G1 X3.540 Y0.043 E0.07881
G1 X3.287 Y0.297 E0.14336
G1 X3.067 Y0.114 E0.19484
G1 X3.526 Y-0.346 E0.31183
G1 X3.478 Y-0.700 E0.37628
G1 X2.847 Y-0.069 E0.53702
G1 X2.627 Y-0.252 E0.58851
G1 X3.356 Y-0.980 E0.77396
G1 X3.136 Y-1.163 E0.82545
G1 X2.407 Y-0.435 E1.01090
G1 X2.187 Y-0.618 E1.06238
G1 X2.916 Y-1.346 E1.24784
G1 X2.696 Y-1.529 E1.29932
G1 X1.967 Y-0.801 E1.48478
G1 X1.748 Y-0.984 E1.53626
G1 X2.476 Y-1.712 E1.72172
G1 X2.256 Y-1.895 E1.77320
G1 X1.528 Y-1.167 E1.95866
G1 X1.308 Y-1.349 E2.01014
G1 X2.036 Y-2.078 E2.19560
G1 X1.817 Y-2.261 E2.24708
G1 X1.088 Y-1.532 E2.43254
G1 X0.868 Y-1.715 E2.48402
G1 X1.597 Y-2.444 E2.66948
G1 X1.377 Y-2.627 E2.72096
G1 X0.648 Y-1.898 E2.90642
G1 X0.428 Y-2.081 E2.95790
G1 X1.157 Y-2.810 E3.14335
G1 X0.937 Y-2.993 E3.19484
G1 X0.209 Y-2.264 E3.38029
G1 X-0.011 Y-2.447 E3.43178
G1 X0.717 Y-3.176 E3.61723
G1 X0.497 Y-3.359 E3.66872
G1 X-0.231 Y-2.630 E3.85417
G1 X-0.451 Y-2.813 E3.90566
G1 X0.268 Y-3.532 E4.08862
G1 X-0.126 Y-3.541 E4.15942
G1 X-0.671 Y-2.996 E4.29825
G1 X-0.891 Y-3.179 E4.34973
G1 X-0.572 Y-3.498 E4.43084
G1 X-1.110 Y-3.362 E4.53077
G92 E0
G1 X-2.350 Y-2.643 F480.000
G1 F420
G1 X-2.127 Y-2.455 E0.05249
G1 X-1.398 Y-3.183 E0.23795
G1 X-1.174 Y-2.997 E0.29047
G1 X-1.902 Y-2.268 E0.47593
G1 X-1.678 Y-2.081 E0.52846
G1 X-0.950 Y-2.810 E0.71391
G1 X-0.725 Y-2.623 E0.76644
G1 X-1.454 Y-1.895 E0.95190
G1 X-1.230 Y-1.708 E1.00442
G1 X-0.501 Y-2.437 E1.18988
G1 X-0.277 Y-2.250 E1.24241
G1 X-1.005 Y-1.521 E1.42786
G1 X-0.781 Y-1.335 E1.48039
G1 X-0.052 Y-2.063 E1.66585
G1 X0.172 Y-1.877 E1.71837
G1 X-0.557 Y-1.148 E1.90383
G1 X-0.332 Y-0.962 E1.95635
G1 X0.396 Y-1.690 E2.14181
G1 X0.621 Y-1.503 E2.19434
G1 X-0.108 Y-0.775 E2.37979
G1 X0.116 Y-0.588 E2.43232
G1 X0.845 Y-1.317 E2.61778
G1 X1.069 Y-1.130 E2.67030
G1 X0.341 Y-0.402 E2.85576
G1 X0.565 Y-0.215 E2.90829
G1 X1.294 Y-0.943 E3.09374
G1 X1.518 Y-0.757 E3.14627
G1 X0.789 Y-0.028 E3.33173
G1 X1.014 Y0.158 E3.38426
G1 X1.742 Y-0.570 E3.56971
G1 X1.967 Y-0.384 E3.62224
G1 X1.238 Y0.345 E3.80770
G1 X1.462 Y0.532 E3.86022
G1 X2.191 Y-0.197 E4.04568
G1 X2.415 Y-0.010 E4.09821
G1 X1.687 Y0.718 E4.28366
G1 X1.911 Y0.905 E4.33619
G1 X2.639 Y0.176 E4.52165
G1 X2.864 Y0.363 E4.57417
G1 X2.135 Y1.092 E4.75963
G1 X2.360 Y1.278 E4.81216
G1 X3.088 Y0.550 E4.99761
G1 X3.312 Y0.736 E5.05014
G1 X2.584 Y1.465 E5.23560
G1 X2.808 Y1.652 E5.28813
G1 X3.369 Y1.091 E5.43093
G1 X3.242 Y1.436 E5.49715
G1 X3.033 Y1.838 E5.57880
G1 Z1.500 F480.000
G92 E0
G1 X2.550 Y-0.661 F480.000
G1 F420
G1 X-0.797 Y-3.445 E0.78365
G1 X-0.216 Y-3.515 E0.88897
G1 X0.116 Y-3.518 E0.94883
G1 X0.419 Y-3.496 E1.00351
G1 X0.841 Y-3.419 E1.08070
G1 X1.248 Y-3.293 E1.15730
G1 X1.635 Y-3.119 E1.23380
G1 X1.932 Y-2.941 E1.29604

G1 F420
G1 X2.218 Y-2.735 E1.35951
G1 X2.541 Y-2.434 E1.43895

G1 F420
G1 X2.770 Y-2.175 E1.50119
G1 X3.012 Y-1.825 E1.57770
G1 X3.210 Y-1.449 E1.65430
G1 X3.361 Y-1.050 E1.73101
G1 X3.464 Y-0.636 E1.80787
G1 X3.516 Y-0.211 E1.88486
G1 X3.517 Y0.145 E1.94892
G1 X2.584 Y-0.632 E2.16741
G92 E0
G1 X2.405 Y-0.417 F480.000
G1 F420
G1 X-1.357 Y-3.548 E0.86110
G1 X-1.142 Y-3.630 E0.90165
G1 X-0.693 Y-3.739 E0.98290
G1 X-0.234 Y-3.795 E1.06425
G1 X0.125 Y-3.798 E1.12746
G1 X0.455 Y-3.774 E1.18555
G1 X0.908 Y-3.691 E1.26663
G1 X1.102 Y-3.631 E1.30233

G1 F420
G1 X1.347 Y-3.555 E1.34848
G1 X1.765 Y-3.367 E1.43108
G1 X2.159 Y-3.130 E1.51386
G1 X2.396 Y-2.951 E1.56725
G1 X2.686 Y-2.691 E1.63733
G1 X2.990 Y-2.348 E1.71995
G1 X3.251 Y-1.970 E1.80255
G1 X3.371 Y-1.743 E1.84870

G1 F420
G1 X3.465 Y-1.564 E1.88440
G1 X3.628 Y-1.134 E1.96531
G1 X3.739 Y-0.687 E2.04634
G1 X3.796 Y-0.229 E2.12750
G1 X3.797 Y0.233 E2.20878
G1 X3.743 Y0.696 E2.29080
G1 X2.440 Y-0.388 E2.58905
G92 E0
G1 X2.549 Y-1.997 F480.000
G1 F420
G1 X1.501 Y-2.870 E0.24540
G1 X1.148 Y-3.028 E0.31520
G1 X1.002 Y-3.073 E0.34261
G1 X3.079 Y-0.997 E0.87127
G1 X3.197 Y-0.490 E0.96490
G1 X2.706 Y-0.898 E1.07979
G1 X0.390 Y-3.214 E1.66934
G1 X-0.100 Y-3.233 E1.75769
G1 Z1.750 F480.000
G92 E0
G1 X2.267 Y-2.631 F480.000
G1 F420
G1 X1.433 Y-3.325 E0.19101
G1 X1.512 Y-3.449 E0.21685
G1 X1.739 Y-3.339 E0.26112
G1 X2.097 Y-3.124 E0.33461
G1 X2.495 Y-2.818 E0.42293
G1 X2.819 Y-2.494 E0.50347
G1 X3.111 Y-2.122 E0.58680
G1 X3.004 Y-2.018 E0.61303
G1 X2.302 Y-2.602 E0.77373
G92 E0
G1 X1.471 Y-3.385 F480.000
G1 F409.874
G1 X0.619 Y-3.882 E0.19124
G92 E0
G1 X3.056 Y-2.069 F480.000
G1 F406.849
G1 X3.697 Y-1.324 E0.19191
G92 E0
; Filament-specific end gcode 
;END gcode for filament

; Filament-specific end gcode 
;END gcode for filament


G92 E0
G28 X0  ; home X axis
M84     ; disable motors

M104 S0 T1 ; set temperature
; filament used = 57.8mm (0.0cm3)
; total filament cost = 0.0

; avoid_crossing_perimeters = 1
; bed_shape = -200x-200,200x-200,200x200,-200x200
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_connections_width = 0
; brim_width = 0
; complete_objects = 0
; cooling = 0
; default_acceleration = 0
; disable_fan_first_layers = 1
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n";"; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = \nG92 E0\nG28 X0  ; home X axis\nM84     ; disable motors\n
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0,0x0
; extrusion_axis = E
; extrusion_multiplier = 2,2
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #FFFFFF;#FFFFFF
; filament_cost = 0,0
; filament_density = 0,0
; filament_diameter = 1,1
; filament_max_volumetric_speed = 0,0
; filament_notes = ;
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 100%
; first_layer_speed = 100%
; first_layer_temperature = 200,200
; gcode_arcs = 0
; gcode_comments = 0
; gcode_flavor = repetier
; has_heatbed = 0
; infill_acceleration = 0
; infill_first = 0
; interior_brim_width = 0
; label_printed_objects = 0
; layer_gcode = 
; max_fan_speed = 100
; max_layer_height = 0.3,0.3
; max_print_speed = 80
; max_volumetric_speed = 0.52
; min_fan_speed = 35
; min_layer_height = 0.1,0.1
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 0.3,0.3
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; printer_notes = 
; resolution = 0
; retract_before_travel = 0,0
; retract_layer_change = 0,0
; retract_length = 0,0
; retract_length_toolchange = 0,0
; retract_lift = 0,0
; retract_lift_above = 0,0
; retract_lift_below = 0,0
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 0,0
; retract_speed = 1000,1000
; skirt_distance = 6
; skirt_height = 0
; skirts = 0
; slowdown_below_layer_time = 30
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n";"; Filament gcode\n"
; start_gcode = G28 ; Home all axes \nM109 S200 ; wait for temperature to be reached\nG21 ; set units to millimeters\nG90 ; use absolute coordinates\nM82 ; use absolute distances for extrusion\nG1 Z10 F500; move plate down\nG1 Z1.0 F500;\nG92 E0
; temperature = 200,200
; threads = 8
; toolchange_gcode = 
; travel_speed = 8
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_set_and_wait_bed = 0
; use_set_and_wait_extruder = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0,0
; z_offset = 0
; z_steps_per_mm = 0
; adaptive_slicing = 0
; adaptive_slicing_quality = 75%
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.25
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.25
; match_horizontal_surfaces = 0
; raft_layers = 0
; regions_overlap = 0
; seam_position = random
; sequential_print_priority = 0
; support_material = 0
; support_material_angle = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_extrusion_width = 0
; support_material_interface_layers = 0
; support_material_interface_spacing = 0
; support_material_interface_speed = 1
; support_material_max_layers = 0
; support_material_pattern = rectilinear
; support_material_pillar_size = 2.5
; support_material_pillar_spacing = 10
; support_material_spacing = 2.5
; support_material_speed = 1
; support_material_threshold = 60%
; xy_size_compensation = 0
; bottom_infill_pattern = rectilinear
; bottom_solid_layers = 0
; bridge_flow_ratio = 1
; bridge_speed = 7
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 7
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 100%
; fill_gaps = 0
; fill_pattern = rectilinear
; gap_fill_speed = 1
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_overlap = 15
; infill_speed = 7
; min_shell_thickness = 0
; min_top_bottom_shell_thickness = 0
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 7
; perimeters = 1
; small_perimeter_speed = 7
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 1
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_infill_pattern = rectilinear
; top_solid_infill_speed = 1
; top_solid_layers = 0
